-- Run this SQL commands after start up the for first time

INSERT INTO bimestres VALUES (1, 'PRIMER BIMESTRE');
INSERT INTO bimestres VALUES (2, 'SEGUNDO BIMESTRE');
INSERT INTO bimestres VALUES (3, 'TERCER BIMESTRE');
INSERT INTO bimestres VALUES (4, 'CUARTO BIMESTRE');

INSERT INTO anios_academicos VALUES (1, 2020);
INSERT INTO anios_academicos VALUES (2, 2021);
INSERT INTO anios_academicos VALUES (3, 2022);
INSERT INTO anios_academicos VALUES (4, 2023);
INSERT INTO anios_academicos VALUES (5, 2024);
INSERT INTO anios_academicos VALUES (6, 2025);

INSERT INTO niveles_educativos VALUES (1, 'PRIMARIA');
INSERT INTO niveles_educativos VALUES (2, 'SECUNDARIA');

INSERT INTO grados VALUES (1, 'PRIMERO', 1);
INSERT INTO grados VALUES (2, 'SEGUNDO', 1);
INSERT INTO grados VALUES (3, 'TERCERO', 1);
INSERT INTO grados VALUES (4, 'CUARTO', 1);
INSERT INTO grados VALUES (5, 'QUINTO', 1);
INSERT INTO grados VALUES (6, 'SEXTO', 1);
INSERT INTO grados VALUES (7, 'PRIMERO', 2);
INSERT INTO grados VALUES (8, 'SEGUNDO', 2);
INSERT INTO grados VALUES (9, 'TERCERO', 2);
INSERT INTO grados VALUES (10, 'CUARTO', 2);
INSERT INTO grados VALUES (11, 'QUINTO', 2);

INSERT INTO materias VALUES (1, '0001-ART Y CULT', 'ARTE Y CULTURA');
INSERT INTO materias VALUES (2, '0002-CAST SEGNL', 'CASTELLANO COMO SEGUNDA LENGUA');
INSERT INTO materias VALUES (3, '0004-CIENC TEC', 'CIENCIA Y TECNOLOGÍA');
INSERT INTO materias VALUES (4, '0010-DESARR PCC', 'DESARROLLO PERSONAL, CIUDADANÍA Y CÍVICA');
INSERT INTO materias VALUES (5, '014-CCSS', 'CIENCIAS SOCIALES');
INSERT INTO materias VALUES (6, '017-COMU', 'COMUNICACIÓN');
INSERT INTO materias VALUES (7, '031-EFIS', 'EDUCACIÓN FÍSICA');
INSERT INTO materias VALUES (8, '032-ETRA', 'EDUCACIÓN PARA EL TRABAJO');
INSERT INTO materias VALUES (9, '035-EREL', 'EDUCACIÓN RELIGIOSA');
INSERT INTO materias VALUES (10, '057-INGL', 'INGLÉS');
INSERT INTO materias VALUES (11, '063-MATE', 'MATEMÁTICA');
INSERT INTO materias VALUES (12, '0006-DESEN TIC', 'SE DESENVUELVE EN ENTORNOS VIRTUALES GENERADOS POR LAS TIC');
INSERT INTO materias VALUES (13, '0007-GEST AUTO', 'GESTIONA SU APRENDIZAJE DE MANERA AUTÓNOMA');

INSERT INTO secciones VALUES (1, 'A');
INSERT INTO secciones VALUES (2, 'B');
INSERT INTO secciones VALUES (3, 'C');
INSERT INTO secciones VALUES (4, 'D');
INSERT INTO secciones VALUES (5, 'E');
INSERT INTO secciones VALUES (6, 'F');
INSERT INTO secciones VALUES (7, 'G');

INSERT INTO niveles_logro VALUES (1, 'A');
INSERT INTO niveles_logro VALUES (2, 'B');
INSERT INTO niveles_logro VALUES (3, 'C');
INSERT INTO niveles_logro VALUES (4, 'D');
INSERT INTO niveles_logro VALUES (5, 'No calificado');
